/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author reqaw
 */
public class LoginLaundryReserve extends javax.swing.JFrame {

    /**
     * Creates new form LoginLaundryReserve
     */
    public LoginLaundryReserve() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackPanel = new javax.swing.JPanel();
        TopLogin = new javax.swing.JLabel();
        Username = new javax.swing.JLabel();
        Password = new javax.swing.JLabel();
        Usernametxtbox = new javax.swing.JTextField();
        Passwordtxtbox = new javax.swing.JTextField();
        Loginbtn = new javax.swing.JButton();
        BacktoDashbtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Laundry Reserve Login");

        BackPanel.setBackground(new java.awt.Color(255, 255, 255));
        BackPanel.setMinimumSize(new java.awt.Dimension(558, 464));
        BackPanel.setLayout(null);

        TopLogin.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        TopLogin.setForeground(new java.awt.Color(255, 255, 255));
        TopLogin.setText("LOGIN");
        BackPanel.add(TopLogin);
        TopLogin.setBounds(220, 20, 90, 35);

        Username.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Username.setForeground(new java.awt.Color(0, 0, 0));
        Username.setText("Username");
        BackPanel.add(Username);
        Username.setBounds(102, 134, 110, 28);

        Password.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Password.setForeground(new java.awt.Color(0, 0, 0));
        Password.setText("Password");
        BackPanel.add(Password);
        Password.setBounds(102, 224, 115, 28);

        Usernametxtbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernametxtboxActionPerformed(evt);
            }
        });
        BackPanel.add(Usernametxtbox);
        Usernametxtbox.setBounds(102, 168, 366, 26);

        Passwordtxtbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordtxtboxActionPerformed(evt);
            }
        });
        BackPanel.add(Passwordtxtbox);
        Passwordtxtbox.setBounds(102, 254, 366, 26);

        Loginbtn.setBackground(new java.awt.Color(0, 0, 0));
        Loginbtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Loginbtn.setForeground(new java.awt.Color(255, 255, 255));
        Loginbtn.setText("Login");
        BackPanel.add(Loginbtn);
        Loginbtn.setBounds(376, 328, 127, 53);

        BacktoDashbtn.setBackground(new java.awt.Color(0, 0, 0));
        BacktoDashbtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BacktoDashbtn.setForeground(new java.awt.Color(255, 255, 255));
        BacktoDashbtn.setText("Back To Dashboard");
        BackPanel.add(BacktoDashbtn);
        BacktoDashbtn.setBounds(117, 328, 174, 53);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Background.jpeg"))); // NOI18N
        BackPanel.add(jLabel2);
        jLabel2.setBounds(0, 0, 560, 80);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UsernametxtboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernametxtboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernametxtboxActionPerformed

    private void PasswordtxtboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordtxtboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordtxtboxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginLaundryReserve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginLaundryReserve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginLaundryReserve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginLaundryReserve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginLaundryReserve().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackPanel;
    private javax.swing.JButton BacktoDashbtn;
    private javax.swing.JButton Loginbtn;
    private javax.swing.JLabel Password;
    private javax.swing.JTextField Passwordtxtbox;
    private javax.swing.JLabel TopLogin;
    private javax.swing.JLabel Username;
    private javax.swing.JTextField Usernametxtbox;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
