
public class Registration extends javax.swing.JFrame {

    /**
     * Creates new form Registration
     */
    public Registration() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackPanel = new javax.swing.JPanel();
        Usernamelbl = new javax.swing.JLabel();
        Passwordlbl = new javax.swing.JLabel();
        Usernametxt = new javax.swing.JTextField();
        Usernametxt1 = new javax.swing.JTextField();
        BackToLoginbtn = new javax.swing.JButton();
        Registerbtn = new javax.swing.JButton();
        RegLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registration Form");
        getContentPane().setLayout(null);

        BackPanel.setBackground(new java.awt.Color(255, 255, 255));
        BackPanel.setForeground(new java.awt.Color(255, 255, 255));
        BackPanel.setLayout(null);

        Usernamelbl.setBackground(new java.awt.Color(255, 255, 255));
        Usernamelbl.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Usernamelbl.setForeground(new java.awt.Color(0, 0, 0));
        Usernamelbl.setText("Username");
        BackPanel.add(Usernamelbl);
        Usernamelbl.setBounds(110, 30, 160, 30);

        Passwordlbl.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Passwordlbl.setForeground(new java.awt.Color(0, 0, 0));
        Passwordlbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Passwordlbl.setText("Password");
        BackPanel.add(Passwordlbl);
        Passwordlbl.setBounds(110, 120, 150, 30);

        Usernametxt.setForeground(new java.awt.Color(204, 0, 51));
        Usernametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernametxtActionPerformed(evt);
            }
        });
        BackPanel.add(Usernametxt);
        Usernametxt.setBounds(110, 70, 330, 20);

        Usernametxt1.setForeground(new java.awt.Color(204, 0, 51));
        Usernametxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Usernametxt1ActionPerformed(evt);
            }
        });
        BackPanel.add(Usernametxt1);
        Usernametxt1.setBounds(110, 150, 330, 20);

        BackToLoginbtn.setBackground(new java.awt.Color(0, 0, 0));
        BackToLoginbtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BackToLoginbtn.setForeground(new java.awt.Color(255, 255, 255));
        BackToLoginbtn.setText("Back To Login");
        BackToLoginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackToLoginbtnActionPerformed(evt);
            }
        });
        BackPanel.add(BackToLoginbtn);
        BackToLoginbtn.setBounds(80, 220, 170, 40);

        Registerbtn.setBackground(new java.awt.Color(0, 0, 0));
        Registerbtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Registerbtn.setForeground(new java.awt.Color(255, 255, 255));
        Registerbtn.setText("Register");
        BackPanel.add(Registerbtn);
        Registerbtn.setBounds(330, 220, 140, 40);

        getContentPane().add(BackPanel);
        BackPanel.setBounds(0, 80, 560, 390);

        RegLabel.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        RegLabel.setForeground(new java.awt.Color(255, 255, 255));
        RegLabel.setText("REGISTRATION FORM");
        RegLabel.setToolTipText("");
        RegLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(RegLabel);
        RegLabel.setBounds(140, 20, 290, 35);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Background.jpeg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 560, 80);

        setSize(new java.awt.Dimension(572, 501));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BackToLoginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackToLoginbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BackToLoginbtnActionPerformed

    private void Usernametxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Usernametxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Usernametxt1ActionPerformed

    private void UsernametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernametxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackPanel;
    private javax.swing.JButton BackToLoginbtn;
    private javax.swing.JLabel Passwordlbl;
    private javax.swing.JLabel RegLabel;
    private javax.swing.JButton Registerbtn;
    private javax.swing.JLabel Usernamelbl;
    private javax.swing.JTextField Usernametxt;
    private javax.swing.JTextField Usernametxt1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
